apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: resume-app
data:
  DB_HOST: "mysql"
  DB_NAME: "online_resume_system"
  DB_USER: "resume_user"
  DB_PASS: "resume_pass"
  APP_URL: "http://www.maffindi.com"
